/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateEntityRequest {
    /// 
    #[serde(rename = "type")]
    pub r#type: String,
    /// 
    #[serde(rename = "id")]
    pub id: String,
    /// 
    #[serde(rename = "temperature")]
    pub temperature: serde_json::Value,
    /// 
    #[serde(rename = "humidity")]
    pub humidity: serde_json::Value,
    /// 
    #[serde(rename = "location")]
    pub location: serde_json::Value,
}

impl CreateEntityRequest {
    pub fn new(r#type: String, id: String, temperature: serde_json::Value, humidity: serde_json::Value, location: serde_json::Value) -> CreateEntityRequest {
        CreateEntityRequest {
            r#type,
            id,
            temperature,
            humidity,
            location,
        }
    }
}


