/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateRegistrationRequest {
    /// 
    #[serde(rename = "description")]
    pub description: String,
    /// 
    #[serde(rename = "dataProvided")]
    pub data_provided: serde_json::Value,
    /// 
    #[serde(rename = "provider")]
    pub provider: serde_json::Value,
}

impl CreateRegistrationRequest {
    pub fn new(description: String, data_provided: serde_json::Value, provider: serde_json::Value) -> CreateRegistrationRequest {
        CreateRegistrationRequest {
            description,
            data_provided,
            provider,
        }
    }
}


