/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetAttributeDataResponse {
    /// 
    #[serde(rename = "value")]
    pub value: f64,
    /// 
    #[serde(rename = "type")]
    pub r#type: String,
    /// 
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl GetAttributeDataResponse {
    pub fn new(value: f64, r#type: String, metadata: serde_json::Value) -> GetAttributeDataResponse {
        GetAttributeDataResponse {
            value,
            r#type,
            metadata,
        }
    }
}


