/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListSubscriptionsResponse {
    /// 
    #[serde(rename = "id")]
    pub id: String,
    /// 
    #[serde(rename = "description")]
    pub description: String,
    /// 
    #[serde(rename = "subject")]
    pub subject: serde_json::Value,
    /// 
    #[serde(rename = "notification")]
    pub notification: serde_json::Value,
    /// 
    #[serde(rename = "expires")]
    pub expires: String,
    /// 
    #[serde(rename = "status")]
    pub status: String,
    /// 
    #[serde(rename = "throttling")]
    pub throttling: i32,
}

impl ListSubscriptionsResponse {
    pub fn new(id: String, description: String, subject: serde_json::Value, notification: serde_json::Value, expires: String, status: String, throttling: i32) -> ListSubscriptionsResponse {
        ListSubscriptionsResponse {
            id,
            description,
            subject,
            notification,
            expires,
            status,
            throttling,
        }
    }
}


