/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListEntitiesResponse {
    /// 
    #[serde(rename = "type")]
    pub r#type: String,
    /// 
    #[serde(rename = "id")]
    pub id: String,
    /// 
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<serde_json::Value>,
    /// 
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<serde_json::Value>,
}

impl ListEntitiesResponse {
    pub fn new(r#type: String, id: String) -> ListEntitiesResponse {
        ListEntitiesResponse {
            r#type,
            id,
            temperature: None,
            speed: None,
        }
    }
}


