/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NotifyRequest {
    /// 
    #[serde(rename = "subscriptionId")]
    pub subscription_id: String,
    /// 
    #[serde(rename = "data")]
    pub data: Vec<serde_json::Value>,
}

impl NotifyRequest {
    pub fn new(subscription_id: String, data: Vec<serde_json::Value>) -> NotifyRequest {
        NotifyRequest {
            subscription_id,
            data,
        }
    }
}


