/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Options12 {
    #[serde(rename = "keyValues")]
    KeyValues,

}

impl ToString for Options12 {
    fn to_string(&self) -> String {
        match self {
            Self::KeyValues => String::from("keyValues"),
        }
    }
}

impl Default for Options12 {
    fn default() -> Options12 {
        Self::KeyValues
    }
}




