/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Options10 {
    #[serde(rename = "append")]
    Append,
    #[serde(rename = "keyValues")]
    KeyValues,

}

impl ToString for Options10 {
    fn to_string(&self) -> String {
        match self {
            Self::Append => String::from("append"),
            Self::KeyValues => String::from("keyValues"),
        }
    }
}

impl Default for Options10 {
    fn default() -> Options10 {
        Self::Append
    }
}




