/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Options20 {
    #[serde(rename = "count")]
    Count,
    #[serde(rename = "values")]
    Values,

}

impl ToString for Options20 {
    fn to_string(&self) -> String {
        match self {
            Self::Count => String::from("count"),
            Self::Values => String::from("values"),
        }
    }
}

impl Default for Options20 {
    fn default() -> Options20 {
        Self::Count
    }
}




