/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Options23 {
    #[serde(rename = "count")]
    Count,

}

impl ToString for Options23 {
    fn to_string(&self) -> String {
        match self {
            Self::Count => String::from("count"),
        }
    }
}

impl Default for Options23 {
    fn default() -> Options23 {
        Self::Count
    }
}




