/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryRequest {
    /// 
    #[serde(rename = "entities")]
    pub entities: Vec<serde_json::Value>,
    /// 
    #[serde(rename = "attrs")]
    pub attrs: Vec<String>,
    /// 
    #[serde(rename = "expression")]
    pub expression: serde_json::Value,
    /// 
    #[serde(rename = "metadata")]
    pub metadata: Vec<String>,
}

impl QueryRequest {
    pub fn new(entities: Vec<serde_json::Value>, attrs: Vec<String>, expression: serde_json::Value, metadata: Vec<String>) -> QueryRequest {
        QueryRequest {
            entities,
            attrs,
            expression,
            metadata,
        }
    }
}


