/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveEntityTypeResponse {
    /// 
    #[serde(rename = "attrs")]
    pub attrs: serde_json::Value,
    /// 
    #[serde(rename = "count")]
    pub count: i32,
}

impl RetrieveEntityTypeResponse {
    pub fn new(attrs: serde_json::Value, count: i32) -> RetrieveEntityTypeResponse {
        RetrieveEntityTypeResponse {
            attrs,
            count,
        }
    }
}


