/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RetrieveApiResourcesResponse {
    /// URL which points to the entities resource
    #[serde(rename = "entities_url")]
    pub entities_url: String,
    /// URL which points to the types resource
    #[serde(rename = "types_url")]
    pub types_url: String,
    /// URL which points to the subscriptions resource
    #[serde(rename = "subscriptions_url")]
    pub subscriptions_url: String,
    /// URL which points to the registrations resource
    #[serde(rename = "registrations_url")]
    pub registrations_url: String,
}

impl RetrieveApiResourcesResponse {
    pub fn new(entities_url: String, types_url: String, subscriptions_url: String, registrations_url: String) -> RetrieveApiResourcesResponse {
        RetrieveApiResourcesResponse {
            entities_url,
            types_url,
            subscriptions_url,
            registrations_url,
        }
    }
}


