/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateRequest {
    /// 
    #[serde(rename = "actionType")]
    pub action_type: String,
    /// 
    #[serde(rename = "entities")]
    pub entities: Vec<serde_json::Value>,
}

impl UpdateRequest {
    pub fn new(action_type: String, entities: Vec<serde_json::Value>) -> UpdateRequest {
        UpdateRequest {
            action_type,
            entities,
        }
    }
}


