/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAttributeDataRequest {
    /// 
    #[serde(rename = "value")]
    pub value: f64,
    /// 
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl UpdateAttributeDataRequest {
    pub fn new(value: f64, metadata: serde_json::Value) -> UpdateAttributeDataRequest {
        UpdateAttributeDataRequest {
            value,
            metadata,
        }
    }
}


