/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateAttributeValueRequest {
    /// 
    #[serde(rename = "address")]
    pub address: String,
    /// 
    #[serde(rename = "zipCode")]
    pub zip_code: i32,
    /// 
    #[serde(rename = "city")]
    pub city: String,
    /// 
    #[serde(rename = "country")]
    pub country: String,
}

impl UpdateAttributeValueRequest {
    pub fn new(address: String, zip_code: i32, city: String, country: String) -> UpdateAttributeValueRequest {
        UpdateAttributeValueRequest {
            address,
            zip_code,
            city,
            country,
        }
    }
}


