/*
 * FIWARE-NGSI v2 Specification
 *
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateRegistrationRequest {
    /// 
    #[serde(rename = "expires")]
    pub expires: String,
}

impl UpdateRegistrationRequest {
    pub fn new(expires: String) -> UpdateRegistrationRequest {
        UpdateRegistrationRequest {
            expires,
        }
    }
}


